'use client';

import {useCallback,useEffect,useState} from 'react';
import type {CatalogKind} from '@/lib/catalog-api';

type CatalogInput={name:string;slug:string;summary:string;markdown:string;kind:CatalogKind};
type CatalogEntry={id:string;slug:string;name:string;kind:CatalogKind;state:string;latestRevisionNumber:number;updatedAt:string;etag:string};
type Props={mutate:(path:string,method:'POST'|'PATCH'|'DELETE',body?:object,precondition?:string)=>Promise<Response>;errorFor:(response:Response)=>Promise<string>;onStatus:(message:string)=>void;disabled:boolean};
const blank:CatalogInput={name:'',slug:'',summary:'',markdown:'',kind:'item'};
const labels:Record<CatalogKind,string>={item:'Item',weapon:'Vũ khí',armor:'Giáp',material:'Nguyên liệu',fish:'Cá',crop:'Nông sản'};

export default function CatalogManager({mutate,errorFor,onStatus,disabled}:Props){
 const[items,setItems]=useState<CatalogEntry[]>([]);const[selected,setSelected]=useState<string|null>(null);const[draft,setDraft]=useState<CatalogInput>(blank);const[etag,setEtag]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const response=await fetch('/api/v1/admin/catalog/items',{cache:'no-store'});if(response.ok)setItems(await response.json() as CatalogEntry[]);},[]);
 useEffect(()=>{load().catch(()=>undefined);},[load]);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(error){onStatus((error as Error).message);}finally{setBusy(false);}}
 async function select(id:string){if(!id){setSelected(null);setDraft(blank);setEtag(null);return;}await run(async()=>{const response=await fetch(`/api/v1/admin/catalog/items/${id}`,{cache:'no-store'});if(!response.ok)throw Error(await errorFor(response));const data=await response.json() as CatalogInput;setSelected(id);setDraft({name:data.name,slug:data.slug,summary:data.summary,markdown:data.markdown,kind:data.kind});setEtag(response.headers.get('ETag'));});}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft.name.trim()||!draft.slug.trim()||!draft.markdown.trim()){onStatus('Catalog item cần name, slug và nội dung.');return;}await run(async()=>{const response=selected?await mutate(`/api/v1/admin/catalog/items/${selected}`,'PATCH',draft,etag??undefined):await mutate('/api/v1/admin/catalog/items','POST',draft);if(!response.ok)throw Error(await errorFor(response));const data=await response.json() as {id:string;etag?:string};setSelected(selected??data.id);setEtag(response.headers.get('ETag')??data.etag??null);await load();onStatus('Đã lưu catalog draft.');});}
 async function lifecycle(action:'publish'|'unpublish'){if(!selected||!etag){onStatus('Hãy chọn item và tải ETag trước khi thay đổi trạng thái.');return;}await run(async()=>{const response=await mutate(`/api/v1/admin/catalog/items/${selected}/${action}`,'POST',undefined,etag);if(!response.ok)throw Error(await errorFor(response));await select(selected);await load();onStatus(action==='publish'?'Đã publish catalog item.':'Đã unpublish catalog item.');});}
 return <section className="category-manager" aria-labelledby="catalog-admin-heading"><h2 id="catalog-admin-heading">Game Catalog</h2><p>Catalog là nội dung biên tập. Public chỉ đọc revision đã publish; không đồng bộ hoặc ghi trực tiếp vào database Minecraft.</p><div className="category-management-grid"><div><div className="form-row"><button type="button" disabled={disabled||busy} onClick={()=>{setSelected(null);setDraft(blank);setEtag(null);}}>+ Item mới</button><button type="button" disabled={disabled||busy} onClick={()=>load()}>Làm mới</button></div><div className="tile-grid">{items.map(item=><button type="button" className="article-card" key={item.id} onClick={()=>select(item.id)}><strong>{item.name}</strong><small>{item.slug} · {labels[item.kind]??item.kind} · {item.state}</small></button>)}</div></div><form className="form" onSubmit={save}><label>Tên item<input required maxLength={160} value={draft.name} onChange={e=>setDraft(current=>({...current,name:e.target.value}))}/></label><label>Slug<input required maxLength={120} value={draft.slug} onChange={e=>setDraft(current=>({...current,slug:e.target.value}))}/></label><label>Loại<select value={draft.kind} onChange={e=>setDraft(current=>({...current,kind:e.target.value as CatalogKind}))}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Tóm tắt<textarea maxLength={500} value={draft.summary} onChange={e=>setDraft(current=>({...current,summary:e.target.value}))}/></label><label>Markdown<textarea required maxLength={50000} value={draft.markdown} onChange={e=>setDraft(current=>({...current,markdown:e.target.value}))}/></label><div className="form-row"><button type="submit" disabled={disabled||busy}>Lưu Catalog draft</button><button type="button" disabled={disabled||busy||!selected} onClick={()=>lifecycle('publish')}>Publish</button><button type="button" className="danger" disabled={disabled||busy||!selected} onClick={()=>lifecycle('unpublish')}>Unpublish</button></div></form></div></section>;
}
