'use client';

import {useCallback,useEffect,useState} from 'react';

type ComponentInput={itemId:string;quantity:number};
type RecipeInput={name:string;slug:string;summary:string;markdown:string;ingredients:ComponentInput[];outputs:ComponentInput[]};
type RecipeEntry={id:string;slug:string;name:string;state:string;latestRevisionNumber:number;updatedAt:string;etag:string};
type ItemOption={id:string;name:string};
type Props={mutate:(path:string,method:'POST'|'PATCH'|'DELETE',body?:object,precondition?:string)=>Promise<Response>;errorFor:(response:Response)=>Promise<string>;onStatus:(message:string)=>void;disabled:boolean};
const blank:RecipeInput={name:'',slug:'',summary:'',markdown:'',ingredients:[],outputs:[]};

function ComponentFields({label,values,items,onChange}:{label:string;values:ComponentInput[];items:ItemOption[];onChange:(next:ComponentInput[])=>void}){
 return <fieldset className="tag-fieldset"><legend>{label}</legend>{values.map((value,index)=><div className="form-row" key={`${label}-${index}`}><select required value={value.itemId} onChange={event=>onChange(values.map((current,currentIndex)=>currentIndex===index?{...current,itemId:event.target.value}:current))}><option value="">Chọn item</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="number" min={1} max={999} required value={value.quantity} onChange={event=>onChange(values.map((current,currentIndex)=>currentIndex===index?{...current,quantity:Number(event.target.value)}:current))}/><button type="button" className="danger" onClick={()=>onChange(values.filter((_,currentIndex)=>currentIndex!==index))}>Xóa</button></div>)}<button type="button" onClick={()=>onChange([...values,{itemId:'',quantity:1}])}>+ Thêm</button></fieldset>;
}

export default function RecipeManager({mutate,errorFor,onStatus,disabled}:Props){
 const[items,setItems]=useState<ItemOption[]>([]);const[recipes,setRecipes]=useState<RecipeEntry[]>([]);const[selected,setSelected]=useState<string|null>(null);const[draft,setDraft]=useState<RecipeInput>(blank);const[etag,setEtag]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [recipeResponse,itemResponse]=await Promise.all([fetch('/api/v1/admin/catalog/recipes',{cache:'no-store'}),fetch('/api/v1/admin/catalog/items',{cache:'no-store'})]);if(recipeResponse.ok)setRecipes(await recipeResponse.json() as RecipeEntry[]);if(itemResponse.ok){const data=await itemResponse.json() as Array<{id:string;name:string}>;setItems(data.map(item=>({id:item.id,name:item.name})));}},[]);
 useEffect(()=>{load().catch(()=>undefined);},[load]);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(error){onStatus((error as Error).message);}finally{setBusy(false);}}
 async function select(id:string){if(!id){setSelected(null);setDraft(blank);setEtag(null);return;}await run(async()=>{const response=await fetch(`/api/v1/admin/catalog/recipes/${id}`,{cache:'no-store'});if(!response.ok)throw Error(await errorFor(response));const data=await response.json() as RecipeInput;setSelected(id);setDraft({name:data.name,slug:data.slug,summary:data.summary,markdown:data.markdown,ingredients:data.ingredients.map(item=>({itemId:item.itemId,quantity:item.quantity})),outputs:data.outputs.map(item=>({itemId:item.itemId,quantity:item.quantity}))});setEtag(response.headers.get('ETag'));});}
 async function save(event:React.FormEvent){event.preventDefault();if(!draft.name.trim()||!draft.slug.trim()||!draft.markdown.trim()||!draft.ingredients.length||!draft.outputs.length){onStatus('Recipe cần name, slug, nội dung, ingredient và output.');return;}await run(async()=>{const response=selected?await mutate(`/api/v1/admin/catalog/recipes/${selected}`,'PATCH',draft,etag??undefined):await mutate('/api/v1/admin/catalog/recipes','POST',draft);if(!response.ok)throw Error(await errorFor(response));const data=await response.json() as {id:string;etag?:string};setSelected(selected??data.id);setEtag(response.headers.get('ETag')??data.etag??null);await load();onStatus('Đã lưu recipe draft.');});}
 async function lifecycle(action:'publish'|'unpublish'){if(!selected||!etag){onStatus('Hãy chọn recipe và tải ETag trước khi thay đổi trạng thái.');return;}await run(async()=>{const response=await mutate(`/api/v1/admin/catalog/recipes/${selected}/${action}`,'POST',undefined,etag);if(!response.ok)throw Error(await errorFor(response));await select(selected);await load();onStatus(action==='publish'?'Đã publish recipe.':'Đã unpublish recipe.');});}
 return <section className="category-manager" aria-labelledby="recipe-admin-heading"><h2 id="recipe-admin-heading">Catalog Recipes</h2><p>Recipe chỉ publish được khi ingredient và output đều trỏ tới Catalog item đã publish; revision sẽ snapshot item revision hiện tại.</p><div className="category-management-grid"><div><div className="form-row"><button type="button" disabled={disabled||busy} onClick={()=>{setSelected(null);setDraft({...blank});setEtag(null);}}>+ Recipe mới</button><button type="button" disabled={disabled||busy} onClick={()=>load()}>Làm mới</button></div><div className="tile-grid">{recipes.map(recipe=><button type="button" className="article-card" key={recipe.id} onClick={()=>select(recipe.id)}><strong>{recipe.name}</strong><small>{recipe.slug} · {recipe.state} · r{recipe.latestRevisionNumber}</small></button>)}</div></div><form className="form" onSubmit={save}><label>Tên recipe<input required maxLength={160} value={draft.name} onChange={e=>setDraft(current=>({...current,name:e.target.value}))}/></label><label>Slug<input required maxLength={120} value={draft.slug} onChange={e=>setDraft(current=>({...current,slug:e.target.value}))}/></label><label>Tóm tắt<textarea maxLength={500} value={draft.summary} onChange={e=>setDraft(current=>({...current,summary:e.target.value}))}/></label><ComponentFields label="Ingredients" values={draft.ingredients} items={items} onChange={ingredients=>setDraft(current=>({...current,ingredients}))}/><ComponentFields label="Outputs" values={draft.outputs} items={items} onChange={outputs=>setDraft(current=>({...current,outputs}))}/><label>Markdown<textarea required maxLength={50000} value={draft.markdown} onChange={e=>setDraft(current=>({...current,markdown:e.target.value}))}/></label><div className="form-row"><button type="submit" disabled={disabled||busy}>Lưu Recipe draft</button><button type="button" disabled={disabled||busy||!selected} onClick={()=>lifecycle('publish')}>Publish</button><button type="button" className="danger" disabled={disabled||busy||!selected} onClick={()=>lifecycle('unpublish')}>Unpublish</button></div></form></div></section>;
}
