<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../NovaHaven.Application/NovaHaven.Application.csproj"/>
    <ProjectReference Include="../NovaHaven.Infrastructure/NovaHaven.Infrastructure.csproj"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
