import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import {omitRepeatedTitleHeading} from '@/lib/markdown-display';
import {communityApi,communityKindLabels,type CommunityKind} from '@/lib/community-api';
import DemoDataNotice from '@/components/DemoDataNotice';
function isKind(value:string):value is CommunityKind{return ['event','guild','player','housing','leaderboard'].includes(value);}
export default async function CommunityDetail({params}:{params:Promise<{kind:string;slug:string}>}){const {kind,slug}=await params;if(!isKind(kind))return <section className="content"><h1>Không tìm thấy nội dung</h1></section>;try{const item=await communityApi.detail(kind,slug);const m=item.metadata;const markdown=omitRepeatedTitleHeading(item.markdown,item.name);return <article className="content detail"><Link href={`/community/${kind}`}>← {communityKindLabels[kind]}</Link><DemoDataNotice/><p className="eyebrow">{communityKindLabels[kind].toLocaleUpperCase('vi-VN')} · Bản biên tập {item.revision}</p><h1>{item.name}</h1><p className="intro">{item.summary}</p><div className="knowledge-metadata"><strong>Thông tin cộng đồng</strong>{kind==='event'&&<><p>{m.startsAt?new Date(m.startsAt).toLocaleString('vi-VN'):''} – {m.endsAt?new Date(m.endsAt).toLocaleString('vi-VN'):''}</p><p>Sức chứa: {m.capacity??'—'} · Đăng ký: {m.registrationOpen?'đang mở':'đã đóng'}</p>{m.location?<p>Địa điểm: {m.location.name}</p>:null}</>}{kind==='guild'&&<><p>{m.motto}</p>{m.discordUrl?<p><a href={m.discordUrl} rel="noreferrer" target="_blank">Discord của bang hội ↗</a></p>:null}</>}{kind==='player'&&<p>Tên người chơi: {m.handle}</p>}{kind==='housing'&&<p>Chủ công trình: {m.ownerDisplayName}</p>}{kind==='leaderboard'&&<><p>Hạng mục: {m.leaderboardCategory}</p><ol>{m.rows.map(row=><li key={row.rank}><strong>{row.participantName}</strong> — {row.score} điểm{row.note?` · ${row.note}`:''}</li>)}</ol></>}</div><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} skipHtml>{markdown}</ReactMarkdown></div>{kind==='housing'&&m.galleryMarkdown?<div className="markdown"><h2>Bộ sưu tập</h2><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} skipHtml>{m.galleryMarkdown}</ReactMarkdown></div>:null}</article>;}catch{return <section className="content"><Link href={`/community/${kind}`}>← Quay lại</Link><h1>Không tìm thấy nội dung</h1><div className="notice">Nội dung chưa xuất bản hoặc không tồn tại.</div></section>;}}
