#!/usr/bin/env python3
"""Run the pinned BlueMap CLI against a local Java world without a server."""

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
import zipfile
import zlib


ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import render_minecraft_map  # noqa: E402


BLUEMAP_VERSION = "5.16"
BLUEMAP_URL = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.16/bluemap-5.16-cli.jar"
BLUEMAP_SHA256 = "7940d561890373897f8f6be91a52e765461f40e5be4e1c4401004073ee0d2580"
SUPPORTED_DATA_VERSION = 3955
DEFAULT_ORIGIN = "http://127.0.0.1:8100"
MAX_JAR_BYTES = 100 * 1024 * 1024
MAX_LEVEL_BYTES = 16 * 1024 * 1024


def parse_java_major(version_output: str) -> int | None:
    match = re.search(r"\b(?:version\s+\"?|openjdk\s+|java\s+)(\d+)", version_output, re.IGNORECASE)
    return int(match.group(1)) if match else None


def require_java_21(version_output: str) -> int:
    major = parse_java_major(version_output)
    if major != 21:
        found = f"{major}" if major is not None else "không xác định được"
        raise RuntimeError(f"BlueMap CLI 5.16 trong workflow này yêu cầu Java 21; hiện phát hiện Java {found}.")
    return major


def validate_loopback_origin(value: str) -> str:
    try:
        parsed = urllib.parse.urlsplit(value.strip())
        port = parsed.port
    except (ValueError, AttributeError) as error:
        raise ValueError("BlueMap origin không hợp lệ; chỉ nhận HTTP localhost.") from error
    hostname = (parsed.hostname or "").lower()
    if (parsed.scheme != "http" or hostname not in {"127.0.0.1", "localhost", "::1"}
            or parsed.username or parsed.password or parsed.path not in ("", "/")
            or parsed.query or parsed.fragment or (port is not None and not 1 <= port <= 65535)):
        raise ValueError("BlueMap chỉ được phục vụ qua HTTP loopback (127.0.0.1, localhost hoặc ::1).")
    return urllib.parse.urlunsplit(("http", parsed.netloc, "", "", ""))


def _paths_overlap(first: pathlib.Path, second: pathlib.Path) -> bool:
    return first == second or first in second.parents or second in first.parents


def validate_local_root(value: pathlib.Path, repository_root: pathlib.Path = ROOT) -> pathlib.Path:
    """Confine all generated output to the private project cache, including resolved links."""
    repository = repository_root.resolve()
    lexical_private = repository / ".local" / "bluemap"
    for component in (lexical_private.parent, lexical_private):
        is_junction = getattr(component, "is_junction", lambda: False)
        if component.is_symlink() or is_junction():
            raise ValueError("Thư mục .local/bluemap không được là symlink hoặc junction.")
    private_root = (repository / ".local" / "bluemap").resolve()
    public_root = (repository / "apps" / "web" / "public").resolve()
    if not private_root.is_relative_to(repository) or _paths_overlap(private_root, public_root):
        raise ValueError("Thư mục .local/bluemap phải nằm trong project và ngoài web public.")

    candidate = value.expanduser()
    if not candidate.is_absolute():
        candidate = repository / candidate
    candidate = candidate.resolve()
    if not candidate.is_relative_to(private_root) or _paths_overlap(candidate, public_root):
        raise ValueError("BlueMap chỉ được ghi vào project/.local/bluemap, không được ghi vào public web.")
    return candidate


def _hocon_string(value: str) -> str:
    if "\n" in value or "\r" in value or "\0" in value:
        raise ValueError("Đường dẫn world chứa ký tự xuống dòng hoặc NUL không hợp lệ.")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_map_config(world_path: pathlib.Path, spawn_x: int, spawn_z: int) -> str:
    if not isinstance(spawn_x, int) or not isinstance(spawn_z, int):
        raise ValueError("Tọa độ spawn phải là số nguyên.")
    world = str(world_path.resolve()).replace("\\", "/")
    return (
        "# Generated by scripts/bluemap_local.py; this file is managed locally.\n"
        f"world: {_hocon_string(world)}\n"
        'dimension: "minecraft:overworld"\n'
        'name: "Nova Haven"\n'
        "sorting: -100\n"
        f"start-pos: {{ x: {spawn_x}, z: {spawn_z} }}\n"
        "enable-flat-view: false\n"
        "enable-hires: true\n"
        "enable-perspective-view: true\n"
        "enable-free-flight-view: false\n"
        "\n"
    )


def require_mojang_download_consent(core_config: str, explicitly_accepted: bool) -> None:
    configured = re.search(r"(?m)^\s*accept-download\s*:\s*true\s*(?:#.*)?$", core_config)
    if not explicitly_accepted and not configured:
        raise RuntimeError(
            "Trước lần render đầu, BlueMap yêu cầu chấp nhận tải tài nguyên Minecraft của Mojang. "
            "Hãy đọc điều khoản được liên kết trong config/core.conf rồi chạy lại với "
            "--accept-mojang-downloads nếu bạn đồng ý; setup chưa tự bật lựa chọn này."
        )


def extract_world_from_zip(archive_path: pathlib.Path, destination: pathlib.Path) -> pathlib.Path:
    """Extract only level.dat and overworld region files into a new directory."""
    archive_path = archive_path.resolve()
    destination = destination.resolve()
    if destination.exists():
        raise FileExistsError(f"Không ghi đè thư mục world đã tồn tại: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(archive_path) as world_zip:
        level_name, regions = render_minecraft_map._discover_world(world_zip)
        level_info = world_zip.getinfo(level_name)
        if level_info.file_size > 8 * 1024 * 1024:
            raise ValueError("level.dat vượt giới hạn 8 MiB.")

        with tempfile.TemporaryDirectory(prefix="bluemap-world-", dir=destination.parent) as staging:
            world_root = pathlib.Path(staging) / "world"
            world_root.mkdir()
            with world_zip.open(level_info) as source, (world_root / "level.dat").open("xb") as target:
                shutil.copyfileobj(source, target, 1024 * 1024)
            region_dir = world_root / "region"
            region_dir.mkdir()
            for info in regions:
                name = pathlib.PurePosixPath(info.filename).name
                if not re.fullmatch(r"r\.-?\d+\.-?\d+\.mca", name):
                    raise ValueError(f"ZIP entry không phải region overworld hợp lệ: {info.filename}")
                with world_zip.open(info) as source, (region_dir / name).open("xb") as target:
                    shutil.copyfileobj(source, target, 1024 * 1024)
            os.replace(world_root, destination)
    return destination


def inspect_world_directory(world_path: pathlib.Path) -> tuple[int, int, int]:
    if not world_path.is_dir():
        raise ValueError(f"Không tìm thấy thư mục world: {world_path}")
    level_dat = world_path / "level.dat"
    region_dir = world_path / "region"
    if not level_dat.is_file() or not region_dir.is_dir() or not any(region_dir.glob("r.*.*.mca")):
        raise ValueError("World cần có level.dat và ít nhất một file region/r.*.*.mca.")
    if level_dat.stat().st_size > 8 * 1024 * 1024:
        raise ValueError("level.dat vượt giới hạn 8 MiB.")
    try:
        decompressor = zlib.decompressobj(16 + zlib.MAX_WBITS)
        data = decompressor.decompress(level_dat.read_bytes(), MAX_LEVEL_BYTES + 1)
        if len(data) > MAX_LEVEL_BYTES or decompressor.unconsumed_tail:
            raise ValueError("level.dat giải nén vượt giới hạn.")
        data += decompressor.flush()
        if len(data) > MAX_LEVEL_BYTES or not decompressor.eof:
            raise ValueError("level.dat gzip bị lỗi hoặc quá lớn.")
        root = render_minecraft_map.parse_nbt(data)
    except (OSError, zlib.error) as error:
        raise ValueError(f"Không đọc được level.dat: {error}") from error
    metadata = root.get("Data", root) if isinstance(root, dict) else None
    if not isinstance(metadata, dict):
        raise ValueError("level.dat không chứa metadata thế giới hợp lệ.")
    try:
        data_version = int(metadata["DataVersion"])
        spawn_x, spawn_z = int(metadata["SpawnX"]), int(metadata["SpawnZ"])
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError("level.dat thiếu DataVersion hoặc tọa độ spawn.") from error
    if data_version != SUPPORTED_DATA_VERSION:
        raise ValueError(
            f"World có DataVersion {data_version}; bản BlueMap đã ghim chỉ được xác minh với "
            f"DataVersion {SUPPORTED_DATA_VERSION} (Minecraft 1.21.1)."
        )
    return data_version, spawn_x, spawn_z


def _world_content_files(world_path: pathlib.Path) -> list[pathlib.Path]:
    level_dat = world_path / "level.dat"
    region_dir = world_path / "region"
    if level_dat.is_symlink() or region_dir.is_symlink():
        raise ValueError("Snapshot world không chấp nhận symlink trong level.dat hoặc thư mục region.")
    if not level_dat.is_file() or not region_dir.is_dir():
        raise ValueError("World cần có level.dat và thư mục region.")
    files = [level_dat]
    for region in sorted(region_dir.glob("r.*.*.mca")):
        if not re.fullmatch(r"r\.-?\d+\.-?\d+\.mca", region.name):
            continue
        if region.is_symlink() or not region.is_file():
            raise ValueError(f"File region phải là file thường, không phải symlink: {region.name}")
        files.append(region)
    if len(files) == 1:
        raise ValueError("World cần có ít nhất một file region/r.*.*.mca.")
    return files


def _world_content_sha256(world_path: pathlib.Path, files: list[pathlib.Path]) -> str:
    digest = hashlib.sha256()
    for source in files:
        relative = source.relative_to(world_path).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        expected_size = source.stat().st_size
        digest.update(expected_size.to_bytes(8, "big"))
        observed_size = 0
        with source.open("rb") as stream:
            while chunk := stream.read(1024 * 1024):
                observed_size += len(chunk)
                digest.update(chunk)
        if observed_size != expected_size:
            raise RuntimeError(f"World file changed while hashing: {source}")
    return digest.hexdigest()


def _snapshot_world_directory(source_world: pathlib.Path, local_root: pathlib.Path) -> pathlib.Path:
    source_world = source_world.resolve()
    inspect_world_directory(source_world)
    files = _world_content_files(source_world)
    digest = _world_content_sha256(source_world, files)
    destination = local_root / "world-cache" / digest / "world"
    if destination.exists():
        existing_files = _world_content_files(destination)
        if _world_content_sha256(destination, existing_files) != digest:
            raise RuntimeError(f"Snapshot local không khớp checksum; không ghi đè: {destination}")
        inspect_world_directory(destination)
        return destination

    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="bluemap-snapshot-", dir=destination.parent) as staging:
        staged_world = pathlib.Path(staging) / "world"
        (staged_world / "region").mkdir(parents=True)
        for source in files:
            target = staged_world / source.relative_to(source_world)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
        copied_files = _world_content_files(staged_world)
        if _world_content_sha256(staged_world, copied_files) != digest:
            raise RuntimeError("World nguồn thay đổi trong lúc tạo snapshot; thử lại khi world đã đóng.")
        inspect_world_directory(staged_world)
        os.replace(staged_world, destination)
    return destination


def resolve_world_path(value: str | None, local_root: pathlib.Path) -> pathlib.Path:
    raw = value or os.environ.get("NOVA_MINECRAFT_WORLD")
    if not raw:
        raise ValueError("Hãy truyền --world <thư-mục-world-hoặc-world.zip> hoặc đặt NOVA_MINECRAFT_WORLD.")
    source = pathlib.Path(raw).expanduser().resolve()
    if source.is_dir():
        return _snapshot_world_directory(source, local_root)
    if source.is_file() and source.suffix.lower() == ".zip":
        digest = _file_sha256(source)
        cache_dir = local_root / "world-cache" / digest
        output = cache_dir / "world"
        manifest = cache_dir / "snapshot.sha256"
        if output.exists():
            if not manifest.is_file():
                raise RuntimeError(f"Snapshot ZIP thiếu checksum manifest; từ chối dùng cache: {output}")
            recorded = manifest.read_text(encoding="ascii").splitlines()
            if (len(recorded) != 2 or recorded[0] != digest
                    or not re.fullmatch(r"[0-9a-f]{64}", recorded[1])):
                raise RuntimeError(f"Snapshot ZIP không khớp archive nguồn; từ chối dùng cache: {output}")
            inspect_world_directory(output)
            actual = _world_content_sha256(output, _world_content_files(output))
            if actual != recorded[1]:
                raise RuntimeError(f"Snapshot ZIP không khớp checksum; từ chối dùng cache: {output}")
            return output
        extracted = extract_world_from_zip(source, output)
        snapshot_digest = _world_content_sha256(extracted, _world_content_files(extracted))
        manifest.write_text(f"{digest}\n{snapshot_digest}\n", encoding="ascii", newline="\n")
        return extracted
    raise ValueError(f"--world phải là thư mục world đã giải nén hoặc file ZIP: {source}")


def _file_sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _set_hocon_scalar(path: pathlib.Path, key: str, value: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"BlueMap chưa sinh file cấu hình {path.name}.")
    content = path.read_text(encoding="utf-8")
    pattern = re.compile(rf"(?m)^(\s*{re.escape(key)}\s*:\s*)([^#\r\n]*)(.*)$")
    updated, count = pattern.subn(lambda match: f"{match.group(1)}{value}{match.group(3)}", content, count=1)
    if not count:
        updated = content.rstrip() + f"\n\n# Set locally by scripts/bluemap_local.py\n{key}: {value}\n"
    if updated != content:
        path.write_text(updated, encoding="utf-8", newline="\n")


def ensure_cli(local_root: pathlib.Path) -> tuple[pathlib.Path, str]:
    java = shutil.which("java")
    if not java:
        raise RuntimeError("Không tìm thấy java trong PATH; cần cài Java 21.")
    version = subprocess.run([java, "-version"], capture_output=True, text=True, check=False)
    require_java_21((version.stdout or "") + "\n" + (version.stderr or ""))

    local_root.mkdir(parents=True, exist_ok=True)
    (local_root / "tmp").mkdir(parents=True, exist_ok=True)
    jar_path = local_root / f"bluemap-{BLUEMAP_VERSION}-cli.jar"
    if jar_path.exists():
        digest = hashlib.sha256(jar_path.read_bytes()).hexdigest()
        if digest != BLUEMAP_SHA256:
            raise RuntimeError(f"SHA-256 JAR BlueMap không khớp bản ghim: {jar_path}")
        return jar_path, java

    temporary_path: pathlib.Path | None = None
    try:
        with urllib.request.urlopen(BLUEMAP_URL, timeout=30) as response:
            content_length = response.headers.get("Content-Length")
            if content_length and int(content_length) > MAX_JAR_BYTES:
                raise RuntimeError("JAR BlueMap tải về lớn hơn giới hạn 100 MiB.")
            with tempfile.NamedTemporaryFile(prefix="bluemap-download-", suffix=".jar", dir=local_root, delete=False) as target:
                temporary_path = pathlib.Path(target.name)
                digest = hashlib.sha256()
                size = 0
                while chunk := response.read(1024 * 1024):
                    size += len(chunk)
                    if size > MAX_JAR_BYTES:
                        raise RuntimeError("JAR BlueMap tải về lớn hơn giới hạn 100 MiB.")
                    digest.update(chunk)
                    target.write(chunk)
        if digest.hexdigest() != BLUEMAP_SHA256:
            raise RuntimeError("SHA-256 artifact tải về không khớp release BlueMap 5.16 đã ghim.")
        os.replace(temporary_path, jar_path)
        temporary_path = None
        return jar_path, java
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise RuntimeError(f"Không tải được BlueMap CLI 5.16 từ GitHub Releases: {error}") from error
    finally:
        if temporary_path and temporary_path.exists():
            temporary_path.unlink()


def _configure(local_root: pathlib.Path, jar_path: pathlib.Path, java: str,
               world_path: pathlib.Path, spawn_x: int, spawn_z: int, origin: str) -> pathlib.Path:
    config_dir = local_root / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    core_config = config_dir / "core.conf"
    if not core_config.exists():
        initialized = subprocess.run(
            [java, f"-Djava.io.tmpdir={local_root / 'tmp'}", "-jar", str(jar_path), "-c", str(config_dir)],
            cwd=local_root, check=False,
        )
        if initialized.returncode != 0 and not all(
            (config_dir / name).is_file() for name in ("core.conf", "webapp.conf", "webserver.conf")
        ):
            raise RuntimeError(f"BlueMap không tạo được cấu hình mẫu (exit {initialized.returncode}).")

    core = config_dir / "core.conf"
    webserver = config_dir / "webserver.conf"
    webapp = config_dir / "webapp.conf"
    _set_hocon_scalar(core, "metrics", "false")
    _set_hocon_scalar(webserver, "enabled", "true")
    bind_host = urllib.parse.urlsplit(origin).hostname or "127.0.0.1"
    _set_hocon_scalar(webserver, "ip", _hocon_string(bind_host))
    _set_hocon_scalar(webserver, "port", str(urllib.parse.urlsplit(origin).port or 80))
    _set_hocon_scalar(webapp, "default-to-flat-view", "false")

    maps_dir = config_dir / "maps"
    maps_dir.mkdir(parents=True, exist_ok=True)
    old_map_config = maps_dir / "nova-haven.conf"
    map_config = maps_dir / "nova_haven.conf"
    if old_map_config.is_file() and not map_config.exists():
        old_content = old_map_config.read_text(encoding="utf-8")
        if "Generated by scripts/bluemap_local.py" not in old_content:
            raise RuntimeError(f"Từ chối đổi tên map config chưa được runner quản lý: {old_map_config}")
        os.replace(old_map_config, map_config)
    expected = build_map_config(world_path, spawn_x, spawn_z)
    if map_config.exists() and "Generated by scripts/bluemap_local.py" not in map_config.read_text(encoding="utf-8"):
        raise RuntimeError(f"Từ chối ghi đè map config chưa được runner quản lý: {map_config}")
    if not map_config.exists() or map_config.read_text(encoding="utf-8") != expected:
        map_config.write_text(expected, encoding="utf-8", newline="\n")
    _quarantine_unused_default_maps(local_root, maps_dir)
    return config_dir


def _quarantine_unused_default_maps(local_root: pathlib.Path, maps_dir: pathlib.Path) -> None:
    examples = local_root / "config" / "example-map-configs"
    expected_dimensions = {
        "overworld": "minecraft:overworld",
        "nether": "minecraft:the_nether",
        "end": "minecraft:the_end",
    }
    for map_id, dimension in expected_dimensions.items():
        source = maps_dir / f"{map_id}.conf"
        if not source.is_file():
            continue
        contents = source.read_text(encoding="utf-8")
        if ("Map-Config" not in contents or
                not re.search(r'(?m)^\s*world\s*:\s*"world"\s*$', contents) or
                not re.search(rf'(?m)^\s*dimension\s*:\s*"{re.escape(dimension)}"\s*$', contents)):
            continue
        examples.mkdir(parents=True, exist_ok=True)
        backup = examples / f"{map_id}.conf.template"
        if not backup.exists():
            os.replace(source, backup)


def _cli_command(java: str, jar: pathlib.Path, config: pathlib.Path,
                 local_root: pathlib.Path, *flags: str) -> list[str]:
    temporary_dir = local_root / "tmp"
    temporary_dir.mkdir(parents=True, exist_ok=True)
    return [java, f"-Djava.io.tmpdir={temporary_dir}", "-jar", str(jar), "-c", str(config), *flags]


def _generate_webapp(java: str, jar: pathlib.Path, config: pathlib.Path,
                     local_root: pathlib.Path) -> None:
    result = subprocess.run(
        _cli_command(java, jar, config, local_root, "-g", "-s"), cwd=local_root, check=False,
    )
    webroot = local_root / "web"
    if result.returncode != 0 or not (webroot / "index.html").is_file() or not (webroot / "settings.json").is_file():
        raise RuntimeError("BlueMap không tạo được webapp/settings local; xem log CLI phía trên.")


def _probe(origin: str) -> bool:
    url = validate_loopback_origin(origin) + "/"
    try:
        request = urllib.request.Request(url, method="GET", headers={"Range": "bytes=0-0"})
        with urllib.request.urlopen(request, timeout=1) as response:
            return 200 <= response.status < 300
    except (urllib.error.URLError, TimeoutError, OSError):
        return False


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("setup", "render", "start", "serve", "status"))
    parser.add_argument("--world", help="path to extracted Java world folder or supplied world ZIP")
    parser.add_argument("--origin", default=os.environ.get("NOVA_BLUEMAP_ORIGIN", DEFAULT_ORIGIN), help="local viewer URL (loopback only)")
    parser.add_argument("--accept-mojang-downloads", action="store_true",
                        help="explicitly accept BlueMap downloading Minecraft render resources from Mojang")
    parser.add_argument("--local-root", type=pathlib.Path, default=ROOT / ".local" / "bluemap", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        origin = validate_loopback_origin(args.origin)
        if args.command == "status":
            available = _probe(origin)
            print(f"BlueMap local viewer {'đang chạy' if available else 'chưa chạy'}: {origin}/")
            return 0 if available else 1
        if args.accept_mojang_downloads and args.command not in ("render", "start"):
            raise ValueError("--accept-mojang-downloads chỉ dùng với lệnh render hoặc start.")

        local_root = validate_local_root(args.local_root)
        jar_path, java = ensure_cli(local_root)
        source_world = args.world or os.environ.get("NOVA_MINECRAFT_WORLD")
        world_path = resolve_world_path(args.world, local_root)
        data_version, spawn_x, spawn_z = inspect_world_directory(world_path)
        config_dir = _configure(local_root, jar_path, java, world_path, spawn_x, spawn_z, origin)
        core_config = config_dir / "core.conf"
        if args.accept_mojang_downloads:
            _set_hocon_scalar(core_config, "accept-download", "true")
        if args.command in ("render", "start"):
            require_mojang_download_consent(core_config.read_text(encoding="utf-8"), args.accept_mojang_downloads)
        _generate_webapp(java, jar_path, config_dir, local_root)
        print(f"Java 21 · BlueMap CLI {BLUEMAP_VERSION} · DataVersion {data_version} · spawn X {spawn_x}, Z {spawn_z}")
        print(f"World nguồn (chỉ đọc): {pathlib.Path(source_world or '').expanduser().resolve()}")
        print(f"Snapshot riêng dùng render: {world_path}")
        print(f"Map output/webroot: {local_root / 'web'}")

        if args.command == "setup":
            print(f"Đã cấu hình BlueMap local tại {config_dir}; chưa chạy render.")
            return 0
        flags = {"render": ("-r", "-m", "nova_haven"),
                 "start": ("-r", "-m", "nova_haven", "-w"),
                 "serve": ("-w",)}[args.command]
        return subprocess.run(_cli_command(java, jar_path, config_dir, local_root, *flags),
                              cwd=local_root, check=False).returncode
    except (FileNotFoundError, FileExistsError, OSError, RuntimeError, ValueError, zipfile.BadZipFile) as error:
        print(f"BlueMap local: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
